version: '3'
services:
  postgres:
    image: postgres:alpine
    container_name: udacity-trivia-postgres
    ports:
      - "5432:5432"
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_DB=trivia
      - POSTGRES_USER=caryn
      - POSTGRES_PASSWORD=
      - POSTGRES_PORT=5432
    volumes:
      - ./trivia.psql:/docker-entrypoint-initdb.d/init.sql